### ISSUE TITLE
Installation Issue.

### ISSUE THREAD

**Issue by imayanksrivastava** [waagsociety/citysdk-ld#45]
When i try to run the below command during installation 

 ruby importers/osm/osm_importer.rb -f ~/Downloads/amsterdam_netherlands.osm.pbf -d 

I get the following error: 

root@ns553739:~/citysdk-ld# ruby importers/osm/osm_importer.rb -f ~/Downloads/amsterdam_netherlands.osm.pbf -d osm
importers/osm/osm_importer.rb:99:in `osm2pgsql': undefined method `+@' for #<String:0x0000000190c530> (NoMethodError)
        from importers/osm/osm_importer.rb:180:in `<main>'

**Comment by sbocconi** [comment]
Hello @mayanksrivastav84, do you still have this problem? I cannot reproduce it with a small test I did.
